name: Node CD

on:
  push:
    branches: [ master, cd ]


jobs:

  deploy:

    runs-on: self-hosted

    steps:
    - name: Stop previous pm2 process
      run: pm2 delete --silent maxgage
    - uses: actions/checkout@v2
    - name: Install nodeJS packages
      run: npm i
    - name: Build react app
      run: npm run build
    - name: Start up pm2 instance
      run: pm2 start app.js --name "maxgage"
